# Generated by Django 5.2.1 on 2025-05-11 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
