# Generated by Django 5.2.1 on 2025-05-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultado', '0002_alter_resultado_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
