# Generated by Django 5.2.1 on 2025-05-17 21:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultado', '0003_alter_resultado_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
