# Generated by Django 5.2.1 on 2025-05-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0002_alter_solicitud_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('rev', 'revision de picos')], default='rev', max_length=100),
        ),
    ]
