# Generated by Django 5.2.1 on 2025-05-18 05:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0006_alter_solicitud_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='id',
            field=models.CharField(default=uuid.UUID('2aaa17c4-ddb2-435d-a027-886678529148'), editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('rev', 'revisión de picos')], default='rev', max_length=100),
        ),
    ]
