# Generated by Django 5.2.1 on 2025-05-22 00:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0008_alter_solicitud_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='id',
            field=models.CharField(default=uuid.UUID('0e631b6e-eb36-448c-9ab4-a7547a2be9f5'), editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
