# Generated by Django 5.2.1 on 2025-05-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_is_active_remove_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_d',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
