# Generated by Django 5.2.1 on 2025-05-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_id_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_d',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
