# Generated by Django 5.2.1 on 2025-05-13 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_id_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_d',
        ),
    ]
