# Generated by Django 5.2.1 on 2025-05-11 06:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0001_initial'),
        ('resultado', '0002_alter_resultado_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='examen',
            name='resultado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resultado.resultado'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='tipo',
            field=models.CharField(choices=[('EEG', 'EEG')], max_length=100),
        ),
    ]
