# Generated by Django 5.2.1 on 2025-05-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0002_alter_examen_fecha_alter_examen_resultado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='examenes/'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='tipo',
            field=models.CharField(choices=[('EEG', 'Electroencefalograma')], max_length=100),
        ),
    ]
