# Generated by Django 5.2.1 on 2025-05-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0003_examen_archivo_alter_examen_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='resultado',
        ),
        migrations.AlterField(
            model_name='examen',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='.../../bucket/examenes/'),
        ),
    ]
