# Generated by Django 5.2.1 on 2025-05-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0004_remove_examen_paciente_remove_examen_resultado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='examenes_temp/'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
