# Generated by Django 5.2.1 on 2025-05-12 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0006_alter_examen_archivo'),
        ('paciente', '0003_remove_paciente_sexo'),
        ('resultado', '0002_alter_resultado_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='paciente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
        migrations.AddField(
            model_name='examen',
            name='resultado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resultado.resultado'),
        ),
    ]
