# Generated by Django 5.2.1 on 2025-05-17 21:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0008_alter_examen_id'),
        ('paciente', '0006_alter_paciente_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='archivo',
            field=models.FileField(upload_to='examenes_temp/'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='examen',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
    ]
