# Generated by Django 5.2.1 on 2025-05-17 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0009_alter_examen_archivo_alter_examen_id_and_more'),
        ('resultado', '0004_alter_resultado_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='resultado',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='resultado.resultado'),
        ),
    ]
