# Generated by Django 5.2.1 on 2025-05-15 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_doctor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
    ]
